[package]
name = "sigma"
version = "1.1.0"
edition = "2021"

[dependencies]
ansiterm = "0.12.2"
clap = "4.5.22"
eframe = "0.29.1"
egui = "0.29.1"
flate2 = "1.0.35"
image = "0.25.5"

[build-dependencies]
winresource = "0.1.17"
