[package]
name = "sigma"
version = "1.1.0"
edition = "2021"

[dependencies]
ansiterm = "0.12.2"
clap = "4.5.19"
eframe = "0.29.0"
egui = "0.29.0"
flate2 = "1.0.34"
image = "0.25.2"

[build-dependencies]
winresource = "0.1.17"
